version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Pre-build step"
  build:
    commands:
      - echo "Running build"
      - python dep1.py  # Replace 'train.py' with the actual script you want to run
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '/*'
